### ISSUE TITLE
ModifierMissing with multi-previews

### ISSUE THREAD

**Issue by tananaev** [twitter/compose-rules#123]
**Describe the bug**

Looks like the `ModifierMissing` rule is not able to detect [multipreview](https://developer.android.com/jetpack/compose/tooling/previews#preview-multipreview) usage, so it flags those previews as missing modifiers. If there's a technical issue with detecting it, maybe we can at least have an exclusion by function name. Maybe by regex or even just assume that previews end with "Preview".

**Comment by mrmans0n** [comment]
This project is not maintained, the fork in https://github.com/mrmans0n/compose-rules continued the work.

**Comment by tananaev** [comment]
Moved to https://github.com/mrmans0n/compose-rules/issues/98.
