### ISSUE TITLE
Could not found required artefacts

### ISSUE THREAD

**Issue by jcraane** [twitter/compose-rules#37]
**Describe the bug**
When declaring a dependency on detektPlugins "com.twitter.compose.rules:detekt:0.0.2", the following error occurs after running 'gradle app:detekt':

`
Execution failed for task ':app:detekt'.
> Could not resolve all files for configuration ':app:detektPlugins'.
   > Could not find com.twitter.compose.rules.core:common:0.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/twitter/compose/rules/core/common/0.0.2/common-0.0.2.pom
       - https://repo.maven.apache.org/maven2/com/twitter/compose/rules/core/common/0.0.2/common-0.0.2.pom
       - Output omitted
`

**Expected behavior**
Detekt runs with the Twitter compose rules applied.

**Comment by mrmans0n** [comment]
Working on that today, I am fixing the misconfigured coordinates.

**Comment by mrmans0n** [comment]
They should all be there for 0.0.4-SNAPSHOT (and I'm trying to publish 0.0.4 right now).

**Comment by jcraane** [comment]
Yes, 0.0.4 works now! Thanks!

**Comment by mrmans0n** [comment]
FWIW I made namings consistent for detekt rules and added the list of rules to manually enable in `detekt.yml` in https://github.com/twitter/compose-rules/pull/38/files - just mentioning because you might be interested!
