### ISSUE TITLE
Fixing "PreviewPublic" reports lead to violations of Detekt's "UnusedPrivateMember" Rule

### ISSUE THREAD

**Issue by inktomi** [twitter/compose-rules#55]
**Describe the bug**
The `PreviewPublic` rule here checks that `@Preview` methods are not public. This is valid, and makes sense - they shouldn't be used outside the IDE in general, so the rule makes sense. 

To fix it, simply mark the `@Preview` method `private` - solved. The issue is that Detekt itself has a rule that enforces that private methods are actually used - `UnusedPrivateMember` ([docs](https://detekt.dev/docs/rules/style/#unusedprivatemember)). That rule allows a regex to allow certain method names to pass - so we could ensure that all our preview methods start with "Preview" or similar, but since they're already annotated that seems duplicative. 

**Expected behavior**
Ideally, we could have both rules active. In reality, I don't think we can ensure that `UnusedPrivateMember` isn't triggered when the fix would trigger `PreviewPublic`. 

We could fix this in detekt by adding an annotation regex alongside the method name regex. I opened [a suggestion on Detekt](https://github.com/detekt/detekt/issues/5296) to solve this on their end, but I wanted to also report it here because this is the rule that's new and causing the conflict.

**Comment by mrmans0n** [comment]
The only thing we could do on our end, I think, is to add a comment in the docs saying that this might happen (so folks can know whether to `@Supress("UnusedPrivateMember ")` or deactivate either `UnusedPrivateMember` or our  `PreviewPublic`.

**Comment by inktomi** [comment]
I'm sorry! This was actually an oversight on my end, this is [already documented with a fix in the Compose docs for Detekt](https://detekt.dev/docs/introduction/compose/#unusedprivatemember). 

Basically, we just need to add a suppression for `@Preview` in our detekt config. Sorry for the confusion, but I hope this will help someone else! Thank you for taking a look!

**Comment by kenyee** [comment]
I was looking for that ignoreAnnotation rule in Detekt... knew it was in there but couldn't remember the name 😂 

We probably should add this to our docs for this rule...folks will probably hit it.

**Comment by inktomi** [comment]
Yea, I'll reopen this issue just to track the documentation. Might be worth a quick mention with a link over the Compose guide in Detekt's docs.

**Comment by mrmans0n** [comment]
Who wants to do the honors and add the link to docs/index.md :D

**Comment by kenyee** [comment]
Added a PR to update our docs to link to the Detekt pages...thanks for pointing that out @inktomi 😸

**Comment by inktomi** [comment]
Thank you @kenyee!

**Comment by mrmans0n** [comment]
Closing as #60 landed.
