### ISSUE TITLE
Support `MutableStateFlow` detection

### ISSUE THREAD

**Issue by VincentMasselis** [twitter/compose-rules#62]
### The problem
The current rules allow a `@Composable` function to have a `MutableStateFlow<T>` parameter type which break, IMO, this [rule](https://twitter.github.io/compose-rules/rules/#do-not-use-inherently-mutable-types-as-parameters)

### A solution
Add a line like `"MutableStateFlow<.*>\\??"` into [this file](https://github.com/twitter/compose-rules/blob/main/core-common/src/main/kotlin/com/twitter/rules/core/util/KtParameters.kt)

**Comment by mrmans0n** [comment]
do you mind submitting a PR adding it to that file? Happy to help with a review

**Comment by mrmans0n** [comment]
Maybe `"Mutable.*Flow<.*>\\??"` to cover MutableSharedFlow and others as well? If they have "Mutable" in the name they are up to no good 😬

**Comment by VincentMasselis** [comment]
I agree with you, but I personally prefer to report each type individually for the moment. If the list of `KtParameters.kt` continue to grow, then we could build a precise approach which cover the listed classes
