### ISSUE TITLE
Maven doesn't contains any artifact for the version 0.0.11

### ISSUE THREAD

**Issue by VincentMasselis** [twitter/compose-rules#70]
**Describe the bug**
I'm unable to perform a gradle sync for the version 0.0.11 while 0.0.10 works well

**To Reproduce**
Add this line `detektPlugins "com.twitter.compose.rules:detekt:0.0.11"` into your `dependencies` lamba

**Expected behavior**
A successful gradle sync

**Stacktrace**
```
10: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':core:test:detekt'.
> Could not resolve all files for configuration ':core:test:detektPlugins'.
   > Could not find com.twitter.compose.rules:detekt:0.0.11.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/twitter/compose/rules/detekt/0.0.11/detekt-0.0.11.pom
       - https://repo.maven.apache.org/maven2/com/twitter/compose/rules/detekt/0.0.11/detekt-0.0.11.pom
     Required by:
         project :core:test
```

**Environment**
- Gradle 7.5
- AGP 7.3.0
- Kotlin 1.7.10
- Compose 1.2.1
- Compose compiler 1.3.0

**Comment by mrmans0n** [comment]
The CI job failed releasing the publication, just done it manually. Give it ~1hr or so and the change will be propagated 😄

**Comment by kenyee** [comment]
it takes a little while for it to show up on maven...give it a few hours

**Comment by VincentMasselis** [comment]
No prob folks, I thought the delivery failed while nobody was aware about that ^^

I'll be patient next time :)
