### ISSUE TITLE
Support Multipreview annotations in `ModifierMissing` rule

### ISSUE THREAD

**Issue by msfjarvis** [twitter/compose-rules#91]
**Is your feature request related to a problem? Please describe.**

Compose now supports providing multiple preview annotations through a "proxy" annotation as documented [here](https://developer.android.com/jetpack/compose/tooling#preview-multipreview), and this currently trips the `ModifierMissing` lint since it only checks for the `Preview` annotation.

**Describe the solution you'd like**

One of these two, depending on complexity
- For each annotation on a function, try to find the annotations present on that annotation class and search for `Preview` there
- Add a Detekt input to allow providing the names of Multipreview annotations manually

**Describe alternatives you've considered**

🤷🏼 

**Additional context**

**Comment by mrmans0n** [comment]
I think we can do something like this here: 
- enforce the naming of a multi preview annotation to have "Preview" or "Previews" suffix, via a new rule (these annotations should be pretty clear that they are for previews anyway 🤷 )
- and then filter out the annotations with that prefix in the `ModifierMissing` rule.

**Comment by msfjarvis** [comment]
> and then filter out the annotations with that prefix in the ModifierMissing rule.

I'm assuming you meant suffix here?

Other than that, sounds like a plan! Would it be easier to do this internally or can I send a PR?

**Comment by mrmans0n** [comment]
Haha, yes, I meant suffix 🤦 

No worries, I am already on it. I'll do them incrementally but likely ship them altogether in the next release
